version: "2"
services:
  app:
    build: .
    container_name: node-service
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/learn-japanese-dev
      - TOKEN_SECRET=TlhvN_k16
      - TOKEN_EXPIRED=7d
      - MAJOR_MINOR_PATCH=1.0.0
      - ENV=DEV
      - SERVER_URL=https://warm-chamber-85391.herokuapp.com:3000
    depends_on:
      - mongo
  mongo:
    container_name: mongo-database
    image: mongo
    volumes: 
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
